on:
  push:
    branches:
      - 'main'

name: Publish on Netlify
jobs:
  publish:
    environment: 'Netlify Deploy'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x

    - run: cd blogware && go build
    - run: blogware/blogware -output site

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
