on: [pull_request]

name: Build website
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make deps

      - name: Run Go tests
        run: make test

      - name: Run Go lint
        run: make lint

      - name: Render the site
        run: make render DEST=site
