on: [pull_request]

name: Build website
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.x

      - name: Run Go tests
        run: make test

      - name: Run Go lint
        run: make lint

      - name: Render the site
        run: make render DEST=site
